# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dflash_service_pb2 as dflash__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dflash_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DFlashCloudStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prefill = channel.unary_unary(
                '/dflash.DFlashCloud/Prefill',
                request_serializer=dflash__service__pb2.PrefillRequest.SerializeToString,
                response_deserializer=dflash__service__pb2.PrefillResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/dflash.DFlashCloud/Verify',
                request_serializer=dflash__service__pb2.VerifyRequest.SerializeToString,
                response_deserializer=dflash__service__pb2.VerifyResponse.FromString,
                _registered_method=True)


class DFlashCloudServicer:
    """Missing associated documentation comment in .proto file."""

    def Prefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFlashCloudServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prefill': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefill,
                    request_deserializer=dflash__service__pb2.PrefillRequest.FromString,
                    response_serializer=dflash__service__pb2.PrefillResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=dflash__service__pb2.VerifyRequest.FromString,
                    response_serializer=dflash__service__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dflash.DFlashCloud', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dflash.DFlashCloud', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DFlashCloud:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dflash.DFlashCloud/Prefill',
            dflash__service__pb2.PrefillRequest.SerializeToString,
            dflash__service__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dflash.DFlashCloud/Verify',
            dflash__service__pb2.VerifyRequest.SerializeToString,
            dflash__service__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
